version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:latest
    container_name: opendb
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    restart: unless-stopped
    ports:
        - "5432:5432"
    volumes:
        - .docker/postgres/data:/var/lib/postgresql/data
        - .docker/postgres/scripts:/etc/postgresql/scripts
    networks:
        - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db-data:
